/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.Business.Articles;
import com.mycompany.Business.Contract;
import com.mycompany.Business.Section;
import com.mycompany.tikasmartcontractor.PDFReader;
import static com.mycompany.tikasmartcontractor.PDFReader.extractTableOfContents;
import static com.mycompany.tikasmartcontractor.PDFReader.parseString;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import opennlp.tools.sentdetect.SentenceDetectorME;
import opennlp.tools.sentdetect.SentenceModel;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.parser.ParseContext;
import org.apache.tika.parser.pdf.PDFParser;
import org.apache.tika.sax.BodyContentHandler;
import org.elasticsearch.client.Client;
import org.elasticsearch.node.Node;
import org.json.JSONObject;

/**
 *
 * @author User
 */
public class MainJFrame_WorkingOnIt extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Contract contract;

    public MainJFrame_WorkingOnIt() {
        contract = new Contract();
        initComponents();
        DefaultTableModel dtm = (DefaultTableModel) sectionJTable.getModel();
        int rowCount = sectionJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

    }
    public static boolean isExcel;
    ArrayList<Section> sectionList = new ArrayList<>();

    public String identifyFileTypeUsingFilesProbeContentType(final String fileName) {
        String fileType = "Undetermined";
        final File file = new File(fileName);
        try {
            fileType = Files.probeContentType(file.toPath());
        } catch (IOException ioException) {
            System.out.println(
                    "ERROR: Unable to determine file type for " + fileName
                    + " due to exception " + ioException);
        }
        return fileType;
    }
    String path = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        openCSATFile = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sectionJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sectionContentJTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openCSATFile.setText("Open Contracts");
        openCSATFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCSATFileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Smart Contract Demo");

        sectionJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key", "Value"
            }
        ));
        sectionJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sectionJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sectionJTable);

        sectionContentJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key", "Value"
            }
        ));
        sectionContentJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sectionContentJTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sectionContentJTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Section Detector Table");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Sentences Table");

        jButton1.setText("Put in Elastic Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openCSATFile)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainJPanelLayout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jLabel1))
                            .addGroup(mainJPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addGap(200, 200, 200)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(78, 78, 78))))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openCSATFile))
                .addGap(32, 32, 32)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        getContentPane().add(mainJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openCSATFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCSATFileActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser("C:\\Users\\User\\Documents\\NetBeansProjects\\TikaSmartContractor\\Contracts");
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            path = selectedFile.getAbsolutePath();

            try {
                String fileBool = identifyFileTypeUsingFilesProbeContentType(selectedFile.getName());
                if (!fileBool.contains("pdf")) {
                    JOptionPane.showMessageDialog(null, "The file choosen is not a pdf file.");
                    isExcel = false;
                } else {
                    JOptionPane.showMessageDialog(null, "You have selected a pdf file.");
                    isExcel = true;
                }

                jTextField1.setText(path);

                FileInputStream inputstream = null;
                try {
                    // TODO code application logic here

                    BodyContentHandler handler = new BodyContentHandler(-1);
                    Metadata metadata = new Metadata();
                    inputstream = new FileInputStream(new File(path));
                    ParseContext pcontext = new ParseContext();
                    //parsing the document using PDF parser
                    PDFParser pdfparser = new PDFParser();
                    pdfparser.parse(inputstream, handler, metadata, pcontext);
                    //getting the content of the document
                    System.out.println("Contents of the PDF :" + handler.toString());
                    //getting metadata of the document
                    String pdfContent = handler.toString();
                    pdfContent = handler.toString().replaceAll("(/[^\\da-zA-Z.]/)", "");

                    //Extract Table of Contents
                    String toc = extractTableOfContents(pdfContent);

                    contract.setTableOfContent(toc);
                    System.out.println(toc);
                    ArrayList<String> keys = new ArrayList<>();
                    Boolean containArticle = toc.contains("Article");
                    Boolean containARTICLE = toc.contains("ARTICLE");
                    //For Contract1
                    String[] articleSplit = {};
                    if (containArticle) {
                        articleSplit = toc.split("Article");
                        int i = 0;
                        for (String article : articleSplit) {
                            Articles article1 = new Articles();
                            article1.setArticleNumber(i);
                            article1.setArticleName(article);

                            i++;
                            String sectionSplit[] = article.split("Section");
                            System.out.println(sectionSplit.length);
                            for (String section : sectionSplit) {
                                Section section1 = new Section();
                                section1.setSectionNumber(section);
                                article1.getSectionList().add(section1);
                                System.out.println(section);
                                keys.add(section);
                            }
                        }
                        System.out.println(articleSplit.length);
                    }
                    try {
                        String ffDocumement[] = pdfContent.split("SCHEDULES");

                        for (int i = 0; i < articleSplit.length; i++) {
                            String currentArticle = articleSplit[i];
                            String nextArticle = articleSplit[i + 1];
                            int prevKeysIndex = ffDocumement[1].indexOf(currentArticle);
                            int afterKeysIndex = ffDocumement[1].indexOf(nextArticle);
                            
                            String sample="1 \n\nDefinitions";
                            String sample2="2 \n\nAmount and Terms of Commitments";
                            prevKeysIndex=ffDocumement[1].indexOf(sample);
                            afterKeysIndex = ffDocumement[1].indexOf(sample2);
                            if (prevKeysIndex != -1 && afterKeysIndex != -1) {
                                String value = ffDocumement[1].substring(prevKeysIndex, afterKeysIndex);
                                System.out.println(value);
                            }
                            
                        }
                    } catch (Exception e) {
                    }
                    //For Contract 2

                    if (containARTICLE) {
                        articleSplit = toc.split("ARTICLE");
                        for (String article : articleSplit) {
                            String sectionSplit[] = article.split("Section");
                            System.out.println(sectionSplit.length);
                            for (String section : sectionSplit) {
                                System.out.println(section);
                                keys.add(section);
                            }
                        }

                        System.out.println(articleSplit.length);
                    }

                    String documentText1[] = pdfContent.split("SCHEDULES");
                    JSONObject myObj = new JSONObject();
                    String fullDocument = documentText1[1];
                    fullDocument = fullDocument.replaceAll(" +", " ");
                    Map<Double, String> hmap = new TreeMap<>();

                    for (int i = 0; i < keys.size(); i++) {
                        try {
                            String extractKeys = firstFive(keys.get(i));
                            extractKeys = extractKeys.replaceAll(" ", "");

                            String values = otherThanFive(keys.get(i));
                            if (isNumeric(extractKeys));
                            {
                                hmap.put(Double.parseDouble(extractKeys), values);
                            }

                            String prevKeys = keys.get(i);
                            String afterKeys = keys.get(i + 1);
                            i++;
                            String prevKeysList[] = prevKeys.split("  ");
                            String my = prevKeysList[1].replaceAll("[^a-zA-Z]", "");
                            String finalPrevKeys = prevKeysList[0] + "  " + my;

                            String afterKeysList[] = afterKeys.split("  ");
                            my = afterKeysList[1].replaceAll("[^a-zA-Z]", "");
                            String finalafterKeys = afterKeysList[0] + "  " + my;

                            // prevKeys = prevKeys.replaceAll("\n", "");
                            //afterKeys = afterKeys.replaceAll("\n", "");
                            // prevKeys = prevKeys.replaceAll("[^a-zA-Z]+", " ");
                            // afterKeys = afterKeys.replaceAll("[^a-zA-Z]+", " ");
                            prevKeys = prevKeys.trim().replaceAll(" +", " ");
                            afterKeys = afterKeys.trim().replaceAll(" +", " ");
                            prevKeys = prevKeys.substring(0, prevKeys.length() - 3);
                            afterKeys = afterKeys.substring(0, afterKeys.length() - 3);

                            //For Contract 1 
                            int prevKeysIndex = fullDocument.indexOf(prevKeys);
                            int afterKeysIndex = fullDocument.indexOf(afterKeys);

                            //Search the Numbers not the text works but accuracy will not be great can generate false positive
                            //int prevKeysIndex = fullDocument.indexOf(prevKeysList[0]);
                            //int afterKeysIndex = fullDocument.indexOf(afterKeysList[0]);
                            if (prevKeysIndex < afterKeysIndex) {
                                String value = fullDocument.substring(prevKeysIndex, afterKeysIndex);
                                value = value.replaceAll("\\[", "").replaceAll("\\]", "");
                                value = value.substring(prevKeys.length(), value.length());
                                if (prevKeys.contains("Increased Cost and Reduced Return; Capital Adequacy; Reserves on Eurodollar Rate Loans")) {
                                    System.out.println("Problem");
                                }
                                myObj.put(prevKeys, value);
                                Section section = new Section();
                                section.setSectionNumber(prevKeys);
                                section.setSectionContent(value);
                                sectionList.add(section);
                            }

                        } catch (Exception e) {
                            System.out.print(e.getMessage());
                        }
                    }

                    for (Map.Entry<Double, String> entry1 : hmap.entrySet()) {

                        Double key1 = entry1.getKey();
                        Articles article = new Articles();
                        if (key1.toString().length() == 3) {
                            String value1 = entry1.getValue();

                            article.setArticleNumber(Integer.parseInt(key1.toString().substring(0, 1)));
                            article.setArticleName(value1);
                        }
                        if (key1.toString().length() != 3) {
                            int i = 0;
                            for (Map.Entry<Double, String> entry2 : hmap.entrySet()) {
                                Double key2 = entry2.getKey();
                                String value2 = entry1.getValue();
                                Section section = new Section();

                            }
                        }
                        if (sectionList.size() > 0) {
                            article.setSectionList(sectionList);
                            contract.getArticleList().add(article);
                        }
                    }

                    PrintWriter out = new PrintWriter("MyIndexex1Sample.json");
                    populateTable();
                    out.print(sectionList.toString());
                    out.close();
                    pdfContent = parseString(pdfContent);

                    FileWriter fw11 = new FileWriter("MyContractText.txt");
                    BufferedWriter bw11 = new BufferedWriter(fw11);
                    bw11.write(pdfContent);

                    bw11.close();
                    fw11.close();
                    System.out.println("Metadata of the PDF:");
                    String[] metadataNames = metadata.names();
                    for (String name : metadataNames) {
                        System.out.println(name + " : " + metadata.get(name));
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PDFReader.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        inputstream.close();
                    } catch (IOException ex) {
                        Logger.getLogger(PDFReader.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "You have selected an invalid file");
            }

        }
    }//GEN-LAST:event_openCSATFileActionPerformed

    public String firstFive(String str) {
        return str.length() < 5 ? str : str.substring(0, 5);
    }

    public String otherThanFive(String str) {
        return str.length() < 5 ? str : str.substring(5, str.length() - 1);
    }

    public static boolean isNumeric(String str) {
        try {
            double d = Double.parseDouble(str);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    private void sectionJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionJTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = sectionJTable.getSelectedRow();
        if (selectedRow >= 0) {
            InputStream is = null;
            try {
                Section vs = (Section) sectionJTable.getValueAt(selectedRow, 0);
                String sectionContent = vs.getSectionContent();

                // always start with a model, a model is learned from training data
                is = new FileInputStream("C:\\Users\\User\\Documents\\NetBeansProjects\\TikaSmartContractor\\en-sent.bin");
                SentenceModel model = new SentenceModel(is);
                SentenceDetectorME sdetector = new SentenceDetectorME(model);
                String sentences[] = sdetector.sentDetect(sectionContent);

                // String paraGraphExtract[] = sectionContent.split("\n\n");
                DefaultTableModel dtm = (DefaultTableModel) sectionContentJTable1.getModel();
                int rowCount = sectionContentJTable1.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    dtm.removeRow(i);
                }
                int i = 0;
                for (String m : sentences) {
                    i++;

                    Object row[] = new Object[2];
                    row[0] = i;
                    row[1] = m;
                    //row[0] = vs.getPulse();
                    dtm.addRow(row);
                }
                resizeColumnWidth(sectionContentJTable1);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    is.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_sectionJTableMouseClicked

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    private void sectionContentJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionContentJTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionContentJTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) sectionJTable.getModel();
        int rowCount = sectionJTable.getRowCount();
        dtm.setRowCount(0);
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (Section vs : sectionList) {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getSectionContent();
            //row[0] = vs.getPulse();
            dtm.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_WorkingOnIt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame_WorkingOnIt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton openCSATFile;
    private javax.swing.JTable sectionContentJTable1;
    private javax.swing.JTable sectionJTable;
    // End of variables declaration//GEN-END:variables
}
